/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Images {
  created_at: Generated<Timestamp>;
  file_key: string;
  id: Generated<number>;
  mime_type: string;
  original_name: string;
  size: Int8;
  updated_at: Generated<Timestamp>;
  user_id: number | null;
}

export interface Items {
  created_at: Generated<Timestamp>;
  id: Generated<number>;
  name: string;
  updated_at: Generated<Timestamp>;
}

export interface Users {
  active: Generated<boolean>;
  created_at: Generated<Timestamp>;
  email: string;
  id: Generated<number>;
  name: string;
  password_hash: string;
  updated_at: Generated<Timestamp>;
}

export interface Bosses {
  id: Generated<number>;
  name: string;
  description: string | null;
  difficulty: number;
  budget_ratio: number;
  reward_points: number;
  image_url: string | null;
}

export interface UserMonths {
  id: Generated<number>;
  user_id: number;
  boss_id: number | null;
  year: number;
  month: number;
  budget: number | null;
  household_size: Generated<number>;
  result: string | null;
  score: number | null;
  created_at: Generated<Timestamp>;
  updated_at: Generated<Timestamp>;
}

export interface Expenses {
  id: Generated<number>;
  user_id: number;
  amount: number;
  category: string;
  note: string | null;
  spent_at: Timestamp;
  created_at: Generated<Timestamp>;
}

export interface UserProfiles {
  id: Generated<number>;
  user_id: number;
  total_points: Generated<number>;
  rank: Generated<string>;
  bosses_defeated: Generated<number>;
  created_at: Generated<Timestamp>;
  updated_at: Generated<Timestamp>;
}

export interface DebugDates {
  id: Generated<number>;
  user_id: number;
  current_date: Timestamp;
}

export interface DB {
  images: Images;
  items: Items;
  users: Users;
  bosses: Bosses;
  user_months: UserMonths;
  expenses: Expenses;
  user_profiles: UserProfiles;
  debug_dates: DebugDates;
}
